### ISSUE TITLE
Decide the type of UI required for Python API

### ISSUE THREAD

**Issue by sopu** [loklak/loklak_python_api#39]
Need help here!
We need to decide the type of UI required for python API. 
It could be a tab kind of thing for each kind of API. Still need to think through on it. 
I did not find a tab layout in Gooey pics and examples. 

![qweertretey](https://cloud.githubusercontent.com/assets/6399612/15611013/f376d91a-2445-11e6-8441-022922efadc8.PNG)
^This could also be one of the options

**Comment by sudheesh001** [comment]
I think this layout seems good :)

**Comment by sopu** [comment]
OK finalized :+1:
