### ISSUE TITLE
Create and release a binary for Gooey and upload it as downloadable executable file

### ISSUE THREAD

**Issue by sopu** [loklak/loklak_python_api#43]

**Comment by mariobehling** [comment]
More information why it is needed and what can be done with it, should be in the description.

What is the status of it?

**Comment by mariobehling** [comment]
If this issue is solved with the merge, can it be closed?

**Comment by sudheesh001** [comment]
This issue cannot be resolved on the other operating systems yet and is blocked by an upstream library which we don't know when they'd update.
