### ISSUE TITLE
Check if Gooey works for *nix systems

### ISSUE THREAD

**Issue by sopu** [loklak/loklak_python_api#44]
I am not able to install wxPython for ubuntu 16.04. 
I am not sure if Gooey GUI works for linux and Mac OSX. 
Need to check. Else add a `requirements_windows.txt` for it

**Comment by sopu** [comment]
It seems that wxPython + Gooey (GUI) does not work for *nix systems. 
Adding a requirements_windows.txt for it.

**Comment by mariobehling** [comment]
What about this issue?

**Comment by sudheesh001** [comment]
I think this is failure from the library's side and not on our side, there are problems with the *nix systems and Gooey running on them. I think this is good to close because the backup plan of taking `requirements_windows.txt` has been implemented

**Comment by mariobehling** [comment]
Ok, thanks.
